/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["filters_api_v1_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Research */
        get: operations["stock_research_api_v1_stocks__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock History */
        get: operations["stock_history_api_v1_stocks__symbol__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Overview */
        get: operations["market_overview_api_v1_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_v1_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Portfolio Cash */
        put: operations["update_portfolio_cash_api_v1_portfolio_cash_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Portfolio Position */
        post: operations["create_portfolio_position_api_v1_portfolio_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/positions/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Portfolio Position */
        delete: operations["delete_portfolio_position_api_v1_portfolio_positions__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screens */
        get: operations["screens_api_v1_screens_get"];
        put?: never;
        /** Upsert Screen */
        post: operations["upsert_screen_api_v1_screens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens/{screen_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screen */
        get: operations["screen_api_v1_screens__screen_id__get"];
        put?: never;
        post?: never;
        /** Delete Screen */
        delete: operations["delete_screen_api_v1_screens__screen_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens/{screen_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screen Versions */
        get: operations["screen_versions_api_v1_screens__screen_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens/{screen_id}/versions/{version}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Screen Version */
        post: operations["restore_screen_version_api_v1_screens__screen_id__versions__version__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens/{screen_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Saved Screen */
        post: operations["run_saved_screen_api_v1_screens__screen_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_runs_get"];
        put?: never;
        /** Run Screen */
        post: operations["run_screen_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidate-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Lists */
        get: operations["candidate_lists_api_v1_candidate_lists_get"];
        put?: never;
        /** Create Candidate List */
        post: operations["create_candidate_list_api_v1_candidate_lists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidate-lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Candidate List */
        delete: operations["delete_candidate_list_api_v1_candidate_lists__list_id__delete"];
        options?: never;
        head?: never;
        /** Rename Candidate List */
        patch: operations["rename_candidate_list_api_v1_candidate_lists__list_id__patch"];
        trace?: never;
    };
    "/api/v1/candidate-lists/{list_id}/candidates/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Candidate */
        put: operations["upsert_candidate_api_v1_candidate_lists__list_id__candidates__symbol__put"];
        post?: never;
        /** Delete Candidate */
        delete: operations["delete_candidate_api_v1_candidate_lists__list_id__candidates__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Sets */
        get: operations["compare_sets_api_v1_compare_sets_get"];
        put?: never;
        /** Upsert Compare Set */
        post: operations["upsert_compare_set_api_v1_compare_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare-sets/{compare_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Compare Set */
        delete: operations["delete_compare_set_api_v1_compare_sets__compare_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/screen-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Screen Run Job */
        post: operations["start_screen_run_job_api_v1_jobs_screen_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/market-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Market Refresh Job */
        post: operations["start_market_refresh_job_api_v1_jobs_market_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiMeta */
        ApiMeta: {
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /**
             * Product
             * @default manmankan
             * @constant
             */
            product: "manmankan";
            /** Product Version */
            product_version: string;
            /**
             * Local Only
             * @default true
             */
            local_only: boolean;
            /** Capabilities */
            capabilities: string[];
        };
        /** AsOfSpec */
        AsOfSpec: {
            /**
             * Trade Date
             * @default latest_complete
             */
            trade_date: string | "latest_complete";
            /**
             * Timezone
             * @default Asia/Shanghai
             */
            timezone: string;
            /**
             * Adjustment
             * @default qfq
             * @constant
             */
            adjustment: "qfq";
            /**
             * Freshness Policy
             * @default allow_stale
             * @enum {string}
             */
            freshness_policy: "require_complete" | "allow_stale";
        };
        /** Candidate */
        Candidate: {
            /** List Id */
            list_id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** @default research */
            status: components["schemas"]["CandidateStatus"];
            /**
             * Note
             * @default
             */
            note: string;
            /** Source Run Id */
            source_run_id?: string | null;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CandidateList */
        CandidateList: {
            /** List Id */
            list_id: string;
            /** Name */
            name: string;
            /** Candidates */
            candidates?: components["schemas"]["Candidate"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CandidateListCreateRequest */
        CandidateListCreateRequest: {
            /** Name */
            name: string;
        };
        /** CandidateListRenameRequest */
        CandidateListRenameRequest: {
            /** Name */
            name: string;
        };
        /**
         * CandidateStatus
         * @enum {string}
         */
        CandidateStatus: "research" | "watch" | "selected" | "rejected";
        /** CandidateUpsertRequest */
        CandidateUpsertRequest: {
            /** Name */
            name?: string | null;
            /** @default research */
            status: components["schemas"]["CandidateStatus"];
            /**
             * Note
             * @default
             */
            note: string;
            /** Source Run Id */
            source_run_id?: string | null;
        };
        /** CashUpdateRequest */
        CashUpdateRequest: {
            /** Cash */
            cash: number;
        };
        /** CompareSet */
        CompareSet: {
            /** Compare Id */
            compare_id: string;
            /** Name */
            name: string;
            /** Symbols */
            symbols: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CompareSetUpsertRequest */
        CompareSetUpsertRequest: {
            /** Compare Id */
            compare_id?: string | null;
            /**
             * Name
             * @default 临时对比
             */
            name: string;
            /** Symbols */
            symbols: string[];
        };
        /**
         * ComparisonOperator
         * @enum {string}
         */
        ComparisonOperator: "lt" | "lte" | "gt" | "gte" | "eq" | "ne";
        /** DataCoverage */
        DataCoverage: {
            /**
             * Universe Size
             * @default 0
             */
            universe_size: number;
            /**
             * Evaluated
             * @default 0
             */
            evaluated: number;
            /**
             * Matched
             * @default 0
             */
            matched: number;
            /**
             * Returned
             * @default 0
             */
            returned: number;
            /**
             * Missing
             * @default 0
             */
            missing: number;
            /**
             * Ratio
             * @default 0
             */
            ratio: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Data Cutoff */
            data_cutoff?: string | null;
            /** Missing By Field */
            missing_by_field?: {
                [key: string]: number;
            };
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "partial" | "failed" | "interrupted";
        /** MarketOverviewResponse */
        MarketOverviewResponse: {
            /** Scan */
            scan?: {
                [key: string]: unknown;
            } | null;
            sentiment: components["schemas"]["MarketSentimentResponse"];
            /** Message */
            message?: string | null;
        };
        /** MarketRefreshRequest */
        MarketRefreshRequest: {
            /** @default default */
            scope: components["schemas"]["MarketRefreshScope"];
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Days
             * @default 360
             */
            days: number;
        };
        /**
         * MarketRefreshScope
         * @enum {string}
         */
        MarketRefreshScope: "default" | "all";
        /** MarketSentimentResponse */
        MarketSentimentResponse: {
            /** Ok */
            ok: boolean;
            /** Up Count */
            up_count?: number | null;
            /** Down Count */
            down_count?: number | null;
            /** Flat Count */
            flat_count?: number | null;
            /** Limit Up */
            limit_up?: number | null;
            /** Limit Down */
            limit_down?: number | null;
            /** Median Position 180 */
            median_position_180?: number | null;
            /** Trade Date */
            trade_date?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * MatchMode
         * @enum {string}
         */
        MatchMode: "all" | "any";
        /**
         * NullPolicy
         * @enum {string}
         */
        NullPolicy: "exclude" | "fail";
        /** PortfolioAccountResponse */
        PortfolioAccountResponse: {
            /** Cash */
            cash?: number | null;
            /** Total Market Value */
            total_market_value?: number | null;
            /** Total Assets */
            total_assets?: number | null;
            /** Total Position Pct */
            total_position_pct?: number | null;
            /** Daily Pnl */
            daily_pnl?: number | null;
            /** Total Pnl */
            total_pnl?: number | null;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Ok */
            ok: boolean;
            /** Price Mode */
            price_mode: string;
            /** Data Cutoff */
            data_cutoff?: string | null;
            account: components["schemas"]["PortfolioAccountResponse"];
            /** Rows */
            rows?: components["schemas"]["PortfolioRowResponse"][];
            /** Notes */
            notes?: string[];
            /** Error */
            error?: string | null;
        };
        /** PortfolioRowResponse */
        PortfolioRowResponse: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Cost */
            cost?: number | null;
            /** Shares */
            shares: number;
            /** Price */
            price?: number | null;
            /** Prev Close */
            prev_close?: number | null;
            /** Market Value */
            market_value?: number | null;
            /** Daily Pnl */
            daily_pnl?: number | null;
            /** Daily Pnl Pct */
            daily_pnl_pct?: number | null;
            /** Total Pnl */
            total_pnl?: number | null;
            /** Total Pnl Pct */
            total_pnl_pct?: number | null;
            /** Weight Pct */
            weight_pct?: number | null;
            /** P30 Pct */
            p30_pct?: number | null;
            /** P60 Pct */
            p60_pct?: number | null;
            /** P180 Pct */
            p180_pct?: number | null;
            /** Price Source */
            price_source?: string | null;
            /** Price Status */
            price_status?: string | null;
            /** Position Alert */
            position_alert?: string | null;
            /** Breakeven Price */
            breakeven_price?: number | null;
            /** Distance To Breakeven */
            distance_to_breakeven?: number | null;
        };
        /** PositionCreateRequest */
        PositionCreateRequest: {
            /** Code */
            code: string;
            /** Cost */
            cost: number;
            /** Shares */
            shares: number;
            /** Name */
            name?: string | null;
            /**
             * Merge
             * @default false
             */
            merge: boolean;
        };
        /** RankChange */
        RankChange: {
            /** Symbol */
            symbol: string;
            /** Previous Rank */
            previous_rank: number;
            /** Current Rank */
            current_rank: number;
            /** Delta */
            delta: number;
        };
        /** SavedScreen */
        SavedScreen: {
            /** Screen Id */
            screen_id: string;
            /** Name */
            name: string;
            /** Current Version */
            current_version: number;
            spec: components["schemas"]["ScreenSpec"];
            /** Spec Hash */
            spec_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScreenCondition */
        ScreenCondition: {
            type: components["schemas"]["ScreenFilterType"];
            operator: components["schemas"]["ComparisonOperator"];
            /** Value */
            value: number;
            /** Period */
            period?: number | null;
            /** Level */
            level?: ("low" | "high") | null;
            /** @default exclude */
            null_policy: components["schemas"]["NullPolicy"];
        };
        /** ScreenDiff */
        ScreenDiff: {
            /** Previous Run Id */
            previous_run_id?: string | null;
            /** Added */
            added?: string[];
            /** Removed */
            removed?: string[];
            /** Rank Changes */
            rank_changes?: components["schemas"]["RankChange"][];
        };
        /** ScreenEvidence */
        ScreenEvidence: {
            /** Evidence Ref */
            evidence_ref: string;
            filter_type: components["schemas"]["ScreenFilterType"];
            /** Field Id */
            field_id: string;
            operator: components["schemas"]["ComparisonOperator"];
            /** Threshold */
            threshold: number;
            /** Actual */
            actual: number;
            /**
             * Unit
             * @default
             */
            unit: string;
            /** Period */
            period?: number | null;
            /** Level */
            level?: ("low" | "high") | null;
            /** Data Date */
            data_date?: string | null;
            /** Source */
            source?: string | null;
            /**
             * Formula Version
             * @default find-v1
             */
            formula_version: string;
        };
        /**
         * ScreenFilterType
         * @enum {string}
         */
        ScreenFilterType: "pos" | "resonance" | "gain" | "up_days" | "ma_bias" | "rs_index" | "rs_board" | "pe" | "pb" | "dv" | "roe" | "turnover" | "market_cap" | "volume_ratio" | "moneyflow" | "moneyflow_daily" | "moneyflow_days" | "rsi" | "macd_dif" | "macd" | "kdj_j" | "atr_pct" | "winner" | "streak" | "holders" | "top10" | "north";
        /** ScreenRow */
        ScreenRow: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /** Price */
            price?: number | null;
            /**
             * In Watchlist
             * @default false
             */
            in_watchlist: boolean;
            /** Values */
            values?: {
                [key: string]: string | number | boolean | null;
            };
            /** Positions */
            positions?: {
                [key: string]: number | null;
            };
            /** Evidence */
            evidence?: components["schemas"]["ScreenEvidence"][];
        };
        /** ScreenRun */
        ScreenRun: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Run Id */
            run_id: string;
            /** Screen Id */
            screen_id?: string | null;
            /** Screen Version */
            screen_version?: number | null;
            spec: components["schemas"]["ScreenSpec"];
            /** Spec Hash */
            spec_hash: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Result Hash */
            result_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            coverage: components["schemas"]["DataCoverage"];
            /** Warnings */
            warnings?: string[];
            /** Rows */
            rows?: components["schemas"]["ScreenRow"][];
            diff?: components["schemas"]["ScreenDiff"];
        };
        /** ScreenRunInput */
        ScreenRunInput: {
            spec?: components["schemas"]["ScreenSpec"] | null;
            /** Screen Id */
            screen_id?: string | null;
            /**
             * Persist
             * @default true
             */
            persist: boolean;
        };
        /** ScreenRunRequest */
        ScreenRunRequest: {
            spec: components["schemas"]["ScreenSpec"];
            /**
             * Persist
             * @default true
             */
            persist: boolean;
        };
        /** ScreenSort */
        ScreenSort: {
            /** Field Id */
            field_id: string;
            /** @default asc */
            direction: components["schemas"]["SortDirection"];
            /**
             * Nulls
             * @default last
             * @constant
             */
            nulls: "last";
        };
        /** ScreenSpec */
        ScreenSpec: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Name
             * @default 未命名选股
             */
            name: string;
            universe?: components["schemas"]["UniverseSpec"];
            as_of?: components["schemas"]["AsOfSpec"];
            /** @default all */
            match_mode: components["schemas"]["MatchMode"];
            /** Conditions */
            conditions?: components["schemas"]["ScreenCondition"][];
            /**
             * Exclude St
             * @default false
             */
            exclude_st: boolean;
            /**
             * Exclude Star
             * @default false
             */
            exclude_star: boolean;
            /**
             * Exclude Bj
             * @default false
             */
            exclude_bj: boolean;
            /** Sort */
            sort?: components["schemas"]["ScreenSort"][];
            /** Columns */
            columns?: string[];
            /**
             * Limit
             * @default 100
             */
            limit: number;
        };
        /** ScreenUpsertRequest */
        ScreenUpsertRequest: {
            spec: components["schemas"]["ScreenSpec"];
            /** Screen Id */
            screen_id?: string | null;
        };
        /** ScreenVersion */
        ScreenVersion: {
            /** Screen Id */
            screen_id: string;
            /** Version */
            version: number;
            spec: components["schemas"]["ScreenSpec"];
            /** Spec Hash */
            spec_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SettingsFactsResponse */
        SettingsFactsResponse: {
            /** Data Dir */
            data_dir: string;
            /** Workspace Db */
            workspace_db: string;
            /** Kline Cache Files */
            kline_cache_files: number;
            /** Tushare Endpoint Domain */
            tushare_endpoint_domain: string;
            /** Tushare Configured */
            tushare_configured: boolean;
            /** Tushare Masked */
            tushare_masked?: string | null;
            /**
             * State Backend
             * @enum {string}
             */
            state_backend: "sqlite" | "legacy";
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: "asc" | "desc";
        /** StockResearchResponse */
        StockResearchResponse: {
            /** Available */
            available: boolean;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message?: string | null;
        };
        /**
         * UniverseKind
         * @enum {string}
         */
        UniverseKind: "all" | "watchlist" | "holdings" | "codes" | "industry" | "theme";
        /** UniverseSpec */
        UniverseSpec: {
            /** @default watchlist */
            kind: components["schemas"]["UniverseKind"];
            /** Value */
            value?: string | null;
            /** Codes */
            codes?: string[];
            /** Group */
            group?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceJob */
        WorkspaceJob: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Watermark */
            watermark?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
            /** Error */
            error?: string | null;
            /** Result Ref */
            result_ref?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiMeta"];
                };
            };
        };
    };
    filters_api_v1_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    stock_research_api_v1_stocks__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_history_api_v1_stocks__symbol__history_get: {
        parameters: {
            query?: {
                period?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_overview_api_v1_market_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOverviewResponse"];
                };
            };
        };
    };
    portfolio_api_v1_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    update_portfolio_cash_api_v1_portfolio_cash_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portfolio_position_api_v1_portfolio_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_position_api_v1_portfolio_positions__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsFactsResponse"];
                };
            };
        };
    };
    screens_api_v1_screens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScreen"][];
                };
            };
        };
    };
    upsert_screen_api_v1_screens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScreen"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_api_v1_screens__screen_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScreen"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_screen_api_v1_screens__screen_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_versions_api_v1_screens__screen_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_screen_version_api_v1_screens__screen_id__versions__version__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScreen"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_saved_screen_api_v1_screens__screen_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_runs_get: {
        parameters: {
            query?: {
                screen_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_screen_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_lists_api_v1_candidate_lists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateList"][];
                };
            };
        };
    };
    create_candidate_list_api_v1_candidate_lists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateListCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_candidate_list_api_v1_candidate_lists__list_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_candidate_list_api_v1_candidate_lists__list_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateListRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_candidate_api_v1_candidate_lists__list_id__candidates__symbol__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: string;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_candidate_api_v1_candidate_lists__list_id__candidates__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: string;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_sets_api_v1_compare_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareSet"][];
                };
            };
        };
    };
    upsert_compare_set_api_v1_compare_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareSetUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_compare_set_api_v1_compare_sets__compare_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compare_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_screen_run_job_api_v1_jobs_screen_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRunInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_market_refresh_job_api_v1_jobs_market_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
