"""ManManKan 稳定领域契约。"""

from kan.domain.job import JobStatus, WorkspaceJob
from kan.domain.screen import (
    AsOfSpec,
    Candidate,
    CandidateList,
    CandidateStatus,
    CompareSet,
    ComparisonOperator,
    DataCoverage,
    FilterInputKind,
    MatchMode,
    NullPolicy,
    RankChange,
    SavedScreen,
    ScreenCondition,
    ScreenDiff,
    ScreenEvidence,
    ScreenFilterType,
    ScreenRow,
    ScreenRun,
    ScreenScalar,
    ScreenSort,
    ScreenSpec,
    SortDirection,
    UniverseKind,
    UniverseSpec,
)

__all__ = [
    "AsOfSpec",
    "Candidate",
    "CandidateList",
    "CandidateStatus",
    "CompareSet",
    "ComparisonOperator",
    "DataCoverage",
    "FilterInputKind",
    "JobStatus",
    "MatchMode",
    "NullPolicy",
    "RankChange",
    "SavedScreen",
    "ScreenCondition",
    "ScreenDiff",
    "ScreenEvidence",
    "ScreenFilterType",
    "ScreenRow",
    "ScreenRun",
    "ScreenScalar",
    "ScreenSort",
    "ScreenSpec",
    "SortDirection",
    "UniverseKind",
    "UniverseSpec",
    "WorkspaceJob",
]
